# Generated by Django 2.1.5 on 2019-03-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_posts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='_profile_following_+', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='posts_count',
            field=models.IntegerField(default=0),
        ),
    ]
